[workspace]
authors = [
    "Dan Allan <dallan@bnl.gov>",
    "Brigitta Sipőcz <brigitta.sipocz@gmail.com>",
    "Ross Barnowski <rossbar@caltech.edu>",
    "Kyle Sunden <git@ksunden.space>",
]
channels = ["conda-forge"]
description = "Add a short description here"
name = "executable-tutorials"
platforms = ["linux-64"]
version = "0.1.0"

[feature.base]
platforms = ["linux-64"]

[feature.base.tasks]
build = { cmd = "sphinx-build -M html . _build" }
clean = "rm -rf _build/*"
start = "jupyter lab  --FileContentsManager.preferred_dir tutorials"
test = "bash ./test.sh"

[feature.base.activation]
# Workaround overrides JupyterLab configuration (at the environment level) to
# make double-clicking on a Jupytext Markdown file open that file as a
# notebook. This is important for the development workflow for contributors.
scripts = ["activate.sh"]

[feature.base.dependencies]
python = ">=3.11"
myst-parser = "*"
matplotlib-base = ">=3.9"
jupyterlab = ">=4.2"
jupyterlab-mathjax3 = ">=4.3"
jupyterlab-myst = ">=2.4"
pytest = ">=8.3.5,<9"
nbval = ">=0.11.0,<0.12"
jupytext = ">=1.17.1,<2"
ipympl = ">=0.9"
edrixs = { version = ">=0.1.2", channel = "conda-forge" }
setuptools = "*"

[feature.base.pypi-dependencies]
sphinx = ">=8.0.2"
myst-nb = "*"
jupytext = ">=1.16"
sphinx-book-theme = ">=1.1"
sphinx-copybutton = ">=0.5"
sphinx-design = "*"
pytest-custom_exit_code = "*"

[feature.py312]
platforms = ["linux-64"]

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313]
platforms = ["linux-64"]

[feature.py313.dependencies]
python = "3.13.*"

[environments]
default = ["base"]
py312 = ["base", "py312"]
py313 = ["base", "py313"]
