name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pixi_test:
    name: pixi on ${{ matrix.os }} with ${{ matrix.environment}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run all supported OS for one Python version, then add a few extra scenarios
        os: [ubuntu-latest]
        environment: [py312, py313]
    steps:
    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@19eac09b398e3d0c747adc7921926a6d802df4da  # v0.8.8
      with:
        environments: ${{ matrix.environment }}

    - name: Test all files
      run: pixi run -e ${{ matrix.environment }} test

  pixi_build:
    name: Build static site with pixi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@19eac09b398e3d0c747adc7921926a6d802df4da  # v0.8.8

    - name: Build static site
      run: pixi run build

